#include <ntddk.h>
#include <wdf.h>

#define IOCTL_READ CTL_CODE(FILE_DEVICE_DRIVER, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE CTL_CODE(FILE_DEVICE_DRIVER, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)